// Сгенерировано из philosophy_graph.html — правки вносить сюда, не в исходник.

import './boot-defs.js';
import './core/base-cells.js';
import './core/events.js';
import './core/graph-index.js';
import './core/link-facts.js';
import './core/long-task.js';
import './core/relation-types.js';
import './core/search.js';
import './core/session.js';
import './core/time.js';
import './core/visibility.js';
import './data/mutate.js';
import './data/save.js';
import './dead.js';
import './filters/beyond-filter.js';
import './filters/chains.js';
import './filters/filters.js';
import './graph/click-actions.js';
import './graph/graph-data.js';
import './graph/graph-selection.js';
import './metrics/by-link-type.js';
import './metrics/concept-dynamics.js';
import './metrics/descriptions.js';
import './metrics/format.js';
import './metrics/generativity.js';
import './metrics/graph-cache.js';
import './metrics/link-indexes.js';
import './metrics/network.js';
import './metrics/philosopher.js';
import './metrics/philosophical.js';
import './metrics/rankings.js';
import './metrics/scope-reset.js';
import './metrics/scope-select.js';
import './metrics/scope.js';
import './metrics/similarity-concepts.js';
import './metrics/similarity-philosophers.js';
import './metrics/tension-cache.js';
import './modal/assembly.js';
import './modal/auth.js';
import './modal/concept-view.js';
import './modal/connection-edit.js';
import './modal/connection-view.js';
import './modal/context.js';
import './modal/core.js';
import './modal/descriptions.js';
import './modal/dirty.js';
import './modal/edit-forms.js';
import './modal/edit-rights.js';
import './modal/entry.js';
import './modal/integrity.js';
import './modal/persist.js';
import './modal/philosopher-view.js';
import './modal/profile-concept.js';
import './modal/profile-philosopher.js';
import './modal/search.js';
import './paths/analysis.js';
import './paths/chronology.js';
import './paths/path-descriptions.js';
import './paths/path-ui.js';
import './paths/shortest-path.js';
import './render/canvas-core.js';
import './render/d3-layer.js';
import './render/draw-link.js';
import './render/geometry.js';
import './render/grouping.js';
import './render/interactions.js';
import './render/loop.js';
import './render/metric-visualization.js';
import './render/picking.js';
import './render/render-state.js';
import './render/scene.js';
import './render/selection.js';
import './render/similarity-overlay.js';
import './render/simulation.js';
import './state/edit.js';
import './state/filters.js';
import './state/metrics-scope.js';
import './state/paths.js';
import './state/render.js';
import './state/stats.js';
import './stats/coverage.js';
import './stats/modal.js';
import './stats/results.js';
import './stats/run.js';
import './stats/views/advanced.js';
import './stats/views/comparison.js';
import './stats/views/network.js';
import './stats/views/philosopher.js';
import './stats/views/philosophical.js';
import './stats/views/rankings.js';
import './ui/about.js';
import './ui/export.js';
import './ui/hint.js';
import './ui/legend.js';
import './ui/search-legend.js';
import './ui/search-link.js';
import './ui/search-philosopher.js';
import './util/color.js';
import './util/html.js';
import './util/philosopher-label.js';
import './util/ru.js';
import './widgets/custom-select.js';

import './ui/actions-byname.js';
import './ui/actions-static.js';
import { installDelegation } from './ui/delegation.js';
import './ui/actions-dyn.js';
import { boot } from './boot.js';

installDelegation();      // делегирование: разметка несёт имя действия
boot().catch(err => {
  console.error('запуск не удался:', err);
  const el = document.getElementById('filterStats');
  if (el) el.textContent = 'Ошибка запуска: ' + err.message;
});
