// Сгенерировано из philosophy_graph.html — правки вносить сюда, не в исходник.

import './boot-defs.js';
import './core/graph-index.js';
import './core/labels.js';
import './core/predicates.js';
import './core/session.js';
import './core/visibility.js';
import './data/mutate.js';
import './data/save.js';
import './dead.js';
import './filters/chains.js';
import './filters/filters.js';
import './filters/state.js';
import './graph/click-actions.js';
import './metrics/advanced.js';
import './metrics/cache.js';
import './metrics/data.js';
import './metrics/descriptions.js';
import './metrics/format.js';
import './metrics/generativity.js';
import './metrics/graph-cache.js';
import './metrics/init.js';
import './metrics/network.js';
import './metrics/philosopher.js';
import './metrics/philosophical.js';
import './metrics/rankings.js';
import './metrics/scope.js';
import './metrics/similarity-concepts.js';
import './metrics/similarity-philosophers.js';
import './metrics/thresholds.js';
import './metrics/typed.js';
import './modal/auth.js';
import './modal/concept-edit.js';
import './modal/concept-view.js';
import './modal/connection-edit.js';
import './modal/connection-view.js';
import './modal/context.js';
import './modal/core.js';
import './modal/dirty.js';
import './modal/edit-common.js';
import './modal/entry.js';
import './modal/integrity.js';
import './modal/persist.js';
import './modal/philosopher-edit.js';
import './modal/philosopher-view.js';
import './modal/profile-concept.js';
import './modal/profile-philosopher.js';
import './modal/registry.js';
import './modal/toggles.js';
import './paths/analysis.js';
import './paths/chronology.js';
import './paths/path-ui.js';
import './paths/shortest-path.js';
import './render/canvas-core.js';
import './render/d3-layer.js';
import './render/geometry.js';
import './render/grouping.js';
import './render/interactions.js';
import './render/metric-visualization.js';
import './render/picking.js';
import './render/scene.js';
import './render/selection.js';
import './render/similarity-overlay.js';
import './render/simulation.js';
import './state.js';
import './stats/modal.js';
import './stats/results.js';
import './stats/run.js';
import './stats/views/advanced.js';
import './stats/views/comparison.js';
import './stats/views/network.js';
import './stats/views/philosopher.js';
import './stats/views/philosophical.js';
import './stats/views/rankings.js';
import './ui/custom-select.js';
import './ui/export.js';
import './ui/feedback.js';
import './ui/legend.js';
import './ui/search-core.js';
import './ui/search-legend.js';
import './ui/search-modal.js';
import './util/format.js';
import './util/html.js';
import './util/misc.js';
import './util/ru.js';

import './ui/actions-byname.js';
import './ui/actions-static.js';
import { installDelegation } from './ui/delegation.js';
import './ui/actions-dyn.js';
import { boot } from './boot.js';

installDelegation();      // делегирование: разметка несёт имя действия
boot().catch(err => {
  console.error('запуск не удался:', err);
  const el = document.getElementById('filterStats');
  if (el) el.textContent = 'Ошибка запуска: ' + err.message;
});
